In [2]:
!pip install nltk

   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 15.9 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import pandas as pd
import numpy as np
import re
import nltk
nltk.download('punkt_tab')
pd.set_option('display.max_columns', None)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.


In [5]:
df = pd.read_csv('IMDB_Top250Engmovies2_OMDB_Detailed.csv')
df.head()

Unnamed: 0                     Title  Year     Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1           2             The Godfather  1972         R  24 Mar 1972  175 min   
2           3    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           4           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4           5              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot  \
0  Two imprisoned men bond over a number of years...   
1  The aging patriarch of an organized crime dyna...   
2  The early life and career of Vito Corleone in ...   
3  When the menace known as the Joker emerges fro...   
4  A jury holdout attempts to prevent a miscarria...   

                                     Language  Country  \
0                                     English      USA   
1                     English, Italian, Latin      USA   
2  English, Italian, Spanish, Latin, Sicilian      USA   
3                           English, Mandarin  USA, UK   
4                                     English      USA   

                                              Awards  \
0  Nominated for 7 Oscars. Another 19 wins & 30 n...   
1    Won 3 Oscars. Another 23 wins & 27 nominations.   
2    Won 6 Oscars. Another 10 wins & 20 nominations.   
3  Won 2 Oscars. Another 151 wins & 153 nominations.   
4  Nominated for 3 Oscars. Another 16 wins & 8 no...   

                                              Poster           Ratings.Source  \
0  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
1  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
2  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
3  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
4  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   

  Ratings.Value  Metascore  imdbRating  imdbVotes     imdbID   Type  \
0        9.3/10       80.0         9.3  1,825,626  tt0111161  movie   
1        9.2/10      100.0         9.2  1,243,444  tt0068646  movie   
2        9.0/10       85.0         9.0    856,870  tt0071562  movie   
3        9.0/10       82.0         9.0  1,802,351  tt0468569  movie   
4        8.9/10       96.0         8.9    494,215  tt0050083  movie   

   tomatoMeter  tomatoImage  tomatoRating  tomatoReviews  tomatoFresh  \
0          NaN          NaN           NaN            NaN          NaN   
1          NaN          NaN           NaN            NaN          NaN   
2          NaN          NaN           NaN            NaN          NaN   
3          NaN          NaN           NaN            NaN          NaN   
4          NaN          NaN           NaN            NaN          NaN   

   tomatoRotten  tomatoConsensus  tomatoUserMeter  tomatoUserRating  \
0           NaN              NaN              NaN               NaN   
1           NaN              

In [6]:
len(df)

250

In [7]:
df['Plot'][0]

'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.'

# Data Preprocessing

In [8]:
df['clean_plot'] = df['Plot'].str.lower()
df['clean_plot'] = df['clean_plot'].apply(lambda x: re.sub('[^a-zA-Z]', ' ', x))
df['clean_plot'] = df['clean_plot'].apply(lambda x: re.sub('\s+', ' ', x))
df['clean_plot']

0      two imprisoned men bond over a number of years...
1      the aging patriarch of an organized crime dyna...
2      the early life and career of vito corleone in ...
3      when the menace known as the joker emerges fro...
4      a jury holdout attempts to prevent a miscarria...
                             ...                        
245    the desperate life of a chronic alcoholic is f...
246    a something supervising staff member of a resi...
247    a newspaper editor uses every trick in the boo...
248    an old man makes a long journey by lawn mover ...
249    a mumbai teen reflects on his upbringing in th...
Name: clean_plot, Length: 250, dtype: object

In [11]:
df['clean_plot'] = df['clean_plot'].apply(lambda x: nltk.word_tokenize(x))
df['clean_plot']

0      [two, imprisoned, men, bond, over, a, number, ...
1      [the, aging, patriarch, of, an, organized, cri...
2      [the, early, life, and, career, of, vito, corl...
3      [when, the, menace, known, as, the, joker, eme...
4      [a, jury, holdout, attempts, to, prevent, a, m...
                             ...                        
245    [the, desperate, life, of, a, chronic, alcohol...
246    [a, something, supervising, staff, member, of,...
247    [a, newspaper, editor, uses, every, trick, in,...
248    [an, old, man, makes, a, long, journey, by, la...
249    [a, mumbai, teen, reflects, on, his, upbringin...
Name: clean_plot, Length: 250, dtype: object

In [13]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [16]:
stop_words = nltk.corpus.stopwords.words('english')
plot = []
for sentence in df['clean_plot']:
    temp = []
    for word in sentence:
        if word not in stop_words and len(word) >= 3:
            temp.append(word)
    plot.append(temp)
plot

[['two',
  'imprisoned',
  'men',
  'bond',
  'number',
  'years',
  'finding',
  'solace',
  'eventual',
  'redemption',
  'acts',
  'common',
  'decency'],
 ['aging',
  'patriarch',
  'organized',
  'crime',
  'dynasty',
  'transfers',
  'control',
  'clandestine',
  'empire',
  'reluctant',
  'son'],
 ['early',
  'life',
  'career',
  'vito',
  'corleone',
  'new',
  'york',
  'portrayed',
  'son',
  'michael',
  'expands',
  'tightens',
  'grip',
  'family',
  'crime',
  'syndicate'],
 ['menace',
  'known',
  'joker',
  'emerges',
  'mysterious',
  'past',
  'wreaks',
  'havoc',
  'chaos',
  'people',
  'gotham',
  'dark',
  'knight',
  'must',
  'accept',
  'one',
  'greatest',
  'psychological',
  'physical',
  'tests',
  'ability',
  'fight',
  'injustice'],
 ['jury',
  'holdout',
  'attempts',
  'prevent',
  'miscarriage',
  'justice',
  'forcing',
  'colleagues',
  'reconsider',
  'evidence'],
 ['german',
  'occupied',
  'poland',
  'world',
  'war',
  'oskar',
  'schindler',


In [17]:
df['clean_plot'] = plot

In [18]:
df['clean_plot']

0      [two, imprisoned, men, bond, number, years, fi...
1      [aging, patriarch, organized, crime, dynasty, ...
2      [early, life, career, vito, corleone, new, yor...
3      [menace, known, joker, emerges, mysterious, pa...
4      [jury, holdout, attempts, prevent, miscarriage...
                             ...                        
245    [desperate, life, chronic, alcoholic, followed...
246    [something, supervising, staff, member, reside...
247    [newspaper, editor, uses, every, trick, book, ...
248    [old, man, makes, long, journey, lawn, mover, ...
249    [mumbai, teen, reflects, upbringing, slums, ac...
Name: clean_plot, Length: 250, dtype: object

In [19]:
df.head()

Unnamed: 0                     Title  Year     Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1           2             The Godfather  1972         R  24 Mar 1972  175 min   
2           3    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           4           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4           5              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot  \
0  Two imprisoned men bond over a number of years...   
1  The aging patriarch of an organized crime dyna...   
2  The early life and career of Vito Corleone in ...   
3  When the menace known as the Joker emerges fro...   
4  A jury holdout attempts to prevent a miscarria...   

                                     Language  Country  \
0                                     English      USA   
1                     English, Italian, Latin      USA   
2  English, Italian, Spanish, Latin, Sicilian      USA   
3                           English, Mandarin  USA, UK   
4                                     English      USA   

                                              Awards  \
0  Nominated for 7 Oscars. Another 19 wins & 30 n...   
1    Won 3 Oscars. Another 23 wins & 27 nominations.   
2    Won 6 Oscars. Another 10 wins & 20 nominations.   
3  Won 2 Oscars. Another 151 wins & 153 nominations.   
4  Nominated for 3 Oscars. Another 16 wins & 8 no...   

                                              Poster           Ratings.Source  \
0  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
1  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
2  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
3  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   
4  https://images-na.ssl-images-amazon.com/images...  Internet Movie Database   

  Ratings.Value  Metascore  imdbRating  imdbVotes     imdbID   Type  \
0        9.3/10       80.0         9.3  1,825,626  tt0111161  movie   
1        9.2/10      100.0         9.2  1,243,444  tt0068646  movie   
2        9.0/10       85.0         9.0    856,870  tt0071562  movie   
3        9.0/10       82.0         9.0  1,802,351  tt0468569  movie   
4        8.9/10       96.0         8.9    494,215  tt0050083  movie   

   tomatoMeter  tomatoImage  tomatoRating  tomatoReviews  tomatoFresh  \
0          NaN          NaN           NaN            NaN          NaN   
1          NaN          NaN           NaN            NaN          NaN   
2          NaN          NaN           NaN            NaN          NaN   
3          NaN          NaN           NaN            NaN          NaN   
4          NaN          NaN           NaN            NaN          NaN   

   tomatoRotten  tomatoConsensus  tomatoUserMeter  tomatoUserRating  \
0           NaN              NaN              NaN               NaN   
1           NaN              

In [20]:
df['Genre'] = df['Genre'].apply(lambda x: x.split(','))
df['Actors'] = df['Actors'].apply(lambda x: x.split(',')[:4])
df['Director'] = df['Director'].apply(lambda x: x.split(','))

In [21]:
df["Actors"][0]

['Tim Robbins', ' Morgan Freeman', ' Bob Gunton', ' William Sadler']

In [23]:
columns = ['clean_plot', 'Genre', 'Actors', 'Director']
l = []
for i in range(len(df)):
    words = ''
    for col in columns:
        words += ' '.join(df[col][i]) + ' '
    l.append(words)
l

['two imprisoned men bond number years finding solace eventual redemption acts common decency Crime  Drama Tim Robbins  Morgan Freeman  Bob Gunton  William Sadler Frank Darabont ',
 'aging patriarch organized crime dynasty transfers control clandestine empire reluctant son Crime  Drama Marlon Brando  Al Pacino  James Caan  Richard S. Castellano Francis Ford Coppola ',
 'early life career vito corleone new york portrayed son michael expands tightens grip family crime syndicate Crime  Drama Al Pacino  Robert Duvall  Diane Keaton  Robert De Niro Francis Ford Coppola ',
 'menace known joker emerges mysterious past wreaks havoc chaos people gotham dark knight must accept one greatest psychological physical tests ability fight injustice Action  Crime  Drama Christian Bale  Heath Ledger  Aaron Eckhart  Michael Caine Christopher Nolan ',
 'jury holdout attempts prevent miscarriage justice forcing colleagues reconsider evidence Crime  Drama Martin Balsam  John Fiedler  Lee J. Cobb  E.G. Marshal

In [24]:
df['clean_input'] = l
df = df[['Title', 'clean_input']]
df.head()

Title                                        clean_input
0  The Shawshank Redemption  two imprisoned men bond number years finding s...
1             The Godfather  aging patriarch organized crime dynasty transf...
2    The Godfather: Part II  early life career vito corleone new york portr...
3           The Dark Knight  menace known joker emerges mysterious past wre...
4              12 Angry Men  jury holdout attempts prevent miscarriage just...

# Feature Extraction

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
tfidf = TfidfVectorizer()
features = tfidf.fit_transform(df['clean_input'])

In [26]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(features, features)
print(cosine_sim)

[[1.         0.02328087 0.02163437 ... 0.00312364 0.00302999 0.00280317]
 [0.02328087 1.         0.25644103 ... 0.00326917 0.00317115 0.00293377]
 [0.02163437 0.25644103 1.         ... 0.00303796 0.00294688 0.00272628]
 ...
 [0.00312364 0.00326917 0.00303796 ... 1.         0.00308842 0.00285723]
 [0.00302999 0.00317115 0.00294688 ... 0.00308842 1.         0.00277156]
 [0.00280317 0.00293377 0.00272628 ... 0.00285723 0.00277156 1.        ]]


# Movie Recommendation

In [27]:
index = pd.Series(df['Title'])
index.head()

0    The Shawshank Redemption
1               The Godfather
2      The Godfather: Part II
3             The Dark Knight
4                12 Angry Men
Name: Title, dtype: object

In [28]:
def recommend_movies(title):
    movies = []
    idx = index[index == title].index[0]
    # print(idx)
    score = pd.Series(cosine_sim[idx]).sort_values(ascending=False)
    top10 = list(score.iloc[1:11].index)
    # print(top10)
    
    for i in top10:
        movies.append(df['Title'][i])
    return movies

In [33]:
recommend_movies('The Dark Knight Rises')

['The Dark Knight',
 'Inception',
 'Batman Begins',
 'The Prestige',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Die Hard',
 'Léon: The Professional',
 'Mad Max: Fury Road',
 'Memento',
 'Sin City']

In [34]:
index[index == 'The Dark Knight Rises'].index[0]

51

In [36]:
pd.Series(cosine_sim[3]).sort_values(ascending=False)

3      1.000000
89     0.227968
51     0.212481
40     0.172792
187    0.076834
         ...   
70     0.000000
58     0.000000
30     0.000000
225    0.000000
191    0.000000
Length: 250, dtype: float64

In [38]:
recommend_movies('The Shawshank Redemption')

['Pulp Fiction',
 'Se7en',
 'Unforgiven',
 'The Green Mile',
 'The Treasure of the Sierra Madre',
 'Million Dollar Baby',
 'Rope',
 'Goodfellas',
 'Sling Blade',
 'Up']

In [41]:
recommend_movies('The Avengers')

['Guardians of the Galaxy Vol. 2',
 'Guardians of the Galaxy',
 'Aliens',
 'Spider-Man: Homecoming',
 'Rush',
 'The Martian',
 'Interstellar',
 'Blade Runner',
 'The Thing',
 'Kill Bill: Vol. 1']

In [42]:
len(df)

250